"""empty message

Revision ID: 58ff8d3a60a4
Revises: 
Create Date: 2023-04-06 19:48:29.185527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ff8d3a60a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('platform_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'userinfo', ['user_id'], ['id'])

    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.alter_column('platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('user_game_game_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_game_platform_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_game_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'userinfo', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key(None, 'platform', ['platform_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_game_user_id_fkey', 'userinfo', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_game_platform_id_fkey', 'platform', ['platform_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_game_game_id_fkey', 'game', ['game_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('platform_user_id_fkey', 'userinfo', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
