"""Update user_game table with correct data types

Revision ID: 87dc232c0eb6
Revises: e3b5cc9ab684
Create Date: 2023-04-09 14:50:04.240346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dc232c0eb6'
down_revision = 'e3b5cc9ab684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('external_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'platform', ['platform_id'], ['id'])
        batch_op.drop_column('completion_status')

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_status', sa.VARCHAR(length=20), server_default=sa.text("'Incomplete'::character varying"), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('external_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
