"""empty message

Revision ID: 9d33ec60a983
Revises: 58ff8d3a60a4
Create Date: 2023-04-06 20:23:14.444452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d33ec60a983'
down_revision = '58ff8d3a60a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recommend', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'userinfo', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recommend')
        batch_op.drop_column('completed')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
